apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/sampleappmetrics"
        prometheus.io/port: "8000"
        prometheus.io/scheme: "http"
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        #replace <foobar> with your container registry. Example: contosodemo.azurecr.io
        image: acrforakscanarydemo.azurecr.io/azure-pipelines-canary-k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
